/* Roseglass Castle: playable chapter. Original Storybook Kingdom is preserved. */
(()=>{
"use strict";
const KEY="roseglass_castle_play_v2";
const fresh=()=>({room:"courtyard",items:[],flags:[],coins:0,solved:false});
let game;try{game={...fresh(),...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch{game=fresh()}
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(game))}catch{}};
const has=x=>game.items.includes(x),done=x=>game.flags.includes(x);
const rooms={
courtyard:{name:"Castle Courtyard",sub:"The grand doors are open. A fountain sparkles beneath the castle towers.",people:[],props:[["⛲","Fountain",20,54,"fountain"],["🌹","Rose Arbor",77,54,"rose"],["🚪","Great Doors",50,35,"entrance"]],exits:[["Enter the Grand Hall","hall"],["Royal Gardens","garden"]]},
hall:{name:"Grand Hall",sub:"Candlelight plays across the royal banners. The queen is waiting beside her throne.",people:["queen","mara"],props:[["👑","Royal Throne",49,35,"throne"],["🕰️","Grand Clock",80,48,"clock"],["🖼️","Old Tapestry",20,43,"tapestry"]],exits:[["Courtyard","courtyard"],["Royal Kitchens","kitchen"],["Royal Library","library"],["West Passage","passage"],["Royal Ballroom","ballroom"]]},
kitchen:{name:"Royal Kitchens",sub:"Copper pans gleam above a warm oven. The baker has a problem.",people:["tomas"],props:[["🥧","Honey Tart",34,50,"tart"],["🧺","Delivery Basket",76,53,"basket"],["🔥","Hearth",51,27,"hearth"]],exits:[["Grand Hall","hall"]]},
library:{name:"Royal Library",sub:"Ancient books reach the ceiling. An archivist is studying a very old parchment.",people:["elin"],props:[["📖","Open Book",24,48,"book"],["📚","Hidden Shelf",76,49,"shelf"],["🌍","Celestial Globe",53,32,"globe"]],exits:[["Grand Hall","hall"],["Secret Passage","passage"]]},
passage:{name:"Secret Passage",sub:"The stone corridor is quiet. The old tower waits beyond a sealed door.",people:[],props:[["🔐","Ancient Lock",50,39,"lock"],["🏮","Lantern",26,58,"lantern"],["🪨","Loose Stones",78,58,"stones"]],exits:[["Royal Library","library"],["Old Tower","tower"],["Grand Hall","hall"]]},
tower:{name:"Old Moon Tower",sub:"Moonlight falls across a velvet chest marked with three silver emblems.",people:[],props:[["🎁","Velvet Chest",52,48,"chest"],["⭐","Star Mosaic",77,46,"mosaic"],["🌙","Tower Window",21,33,"window"]],exits:[["Secret Passage","passage"]]},
ballroom:{name:"Royal Ballroom",sub:"Chandeliers glitter overhead. Musicians wait for the royal celebration.",people:[],props:[["💃","Dance Floor",50,58,"dance"],["🎻","Orchestra",22,45,"music"],["✨","Chandelier",79,29,"lights"]],exits:[["Grand Hall","hall"],["Royal Gardens","garden"]]},
garden:{name:"Royal Gardens",sub:"A swan glides across the pond while roses sway in a warm breeze.",people:[],props:[["🦢","Lily Pond",22,57,"pond"],["🌿","Hedge Maze",78,43,"maze"],["🪑","Garden Bench",49,56,"bench"]],exits:[["Courtyard","courtyard"],["Ballroom","ballroom"]]}
};
const people={
queen:{name:"Queen Elowen",skin:"#a46d50",hair:"#281e20",dress:"#805292",crown:"👑",held:"💎"},
mara:{name:"Mara the Maid",skin:"#bc815f",hair:"#382626",dress:"#8c5974",crown:"",held:"🗝️"},
tomas:{name:"Tomas the Baker",skin:"#b17c60",hair:"#473122",dress:"#b27c4b",crown:"",held:"🥧"},
elin:{name:"Elin the Archivist",skin:"#946447",hair:"#252126",dress:"#466b76",crown:"",held:"📜"},
you:{name:"You",skin:"#a66e52",hair:"#372525",dress:"#6b548d",crown:"",held:"✨"}
};
let el,ui={},busy=false,typeInterval;
function actor(id){const p=people[id];return '<button class="rc-actor '+id+'" type="button" data-person="'+id+'" style="--skin:'+p.skin+';--hair:'+p.hair+';--dress:'+p.dress+'" aria-label="Talk to '+p.name+'"><span class="rc-hair"></span><span class="rc-body"></span><span class="rc-leftarm"></span><span class="rc-rightarm"></span><span class="rc-head"></span><span class="rc-eye left"></span><span class="rc-eye right"></span><span class="rc-mouth"></span><span class="rc-crown">'+p.crown+'</span><span class="rc-held">'+p.held+'</span><span class="rc-personname">'+p.name+'</span></button>'}
function stage(ids,pose="",notice="",next,delay=1250){busy=true;ui.actors.innerHTML=ids.map(actor).join("");ui.actors.className="rc-actors rc-"+pose;if(notice)toast(notice,delay+350);setTimeout(()=>{busy=false;ui.actors.className="rc-actors";if(next)next()},delay)}
function toast(t,ms=2400){ui.toast.textContent=t;ui.toast.classList.add("show");clearTimeout(ui.toast._t);ui.toast._t=setTimeout(()=>ui.toast.classList.remove("show"),ms)}
function dialogue(who,text,choices=[["Keep exploring",()=>scene()]]){ui.who.textContent=who;clearInterval(typeInterval);ui.text.textContent="";let i=0;typeInterval=setInterval(()=>{ui.text.textContent=text.slice(0,++i);if(i>=text.length)clearInterval(typeInterval)},12);ui.options.innerHTML="";for(const [label,fn] of choices){const b=document.createElement("button");b.textContent=label;b.onclick=fn;ui.options.appendChild(b)}}
function earn(item){if(!has(item)){game.items.push(item);game.coins+=3;save();toast("Collected "+item+" · +3 coins");hud()}}
function mark(f){if(!done(f)){game.flags.push(f);save()}hud()}
function objective(){if(game.solved)return"The royal ball is underway! Explore freely.";if(!done("queen"))return"Meet Queen Elowen in the Grand Hall.";if(!has("Brass Key"))return"Help the baker and collect the Brass Key.";if(!has("Clock Riddle"))return"Solve Elin’s riddle in the library.";if(!done("opened"))return"Unlock the Secret Passage.";if(!has("Moonstone"))return"Find the Moonstone in the old tower.";return"Return the Moonstone to the Queen."}
function hud(){if(!ui.quest)return;ui.quest.textContent="✨ "+objective();ui.coins.textContent="🪙 "+game.coins;ui.inventory.innerHTML=game.items.length?game.items.map(x=>'<span>'+x+'</span>').join(""):"Nothing collected yet"}
function scene(){const r=rooms[game.room];ui.stage.dataset.room=game.room;ui.title.textContent=r.name;ui.subtitle.textContent=r.sub;ui.actors.className="rc-actors";ui.actors.innerHTML=["you",...r.people].map(actor).join("");ui.spots.innerHTML=r.props.map(([icon,name,x,y,id])=>'<button class="rc-spot" style="left:'+x+'%;top:'+y+'%" data-spot="'+id+'"><b>'+icon+'</b><span>'+name+'</span></button>').join("");ui.spots.querySelectorAll("button").forEach(b=>b.onclick=()=>inspect(b.dataset.spot));ui.doors.innerHTML=r.exits.map(([name,id])=>'<button data-room="'+id+'">🚪 '+name+'</button>').join("");ui.doors.querySelectorAll("button").forEach(b=>b.onclick=()=>move(b.dataset.room));dialogue("Narrator",r.sub,[["Look around",()=>{ui.text.textContent="Select a character, glowing object or doorway.";ui.options.innerHTML=""}],["Just enjoy the scene",()=>{ui.text.textContent="There is nowhere you have to be. Stay as long as you like.";ui.options.innerHTML=""}]]);hud()}
function move(to){if(busy)return;if(to==="tower"&&!done("opened"))return dialogue("Narrator","The tower door is sealed. Solve the library riddle and unlock the passage first.");if(to==="passage"&&!has("Brass Key"))return dialogue("Narrator","You need a Brass Key to enter the secret corridor. Tomas might have found one in the kitchens.");busy=true;ui.fade.classList.add("show");setTimeout(()=>{game.room=to;save();scene();ui.fade.classList.remove("show");busy=false},400)}
function queen(){mark("queen");if(game.solved)return dialogue("Queen Elowen","Welcome, Guardian of Roseglass. The entire castle is celebrating your courage!",[["Join the royal ball",()=>move("ballroom")],["Explore the castle",scene]]);if(has("Moonstone"))return stage(["you","queen"],"give","You present the glowing Moonstone to the queen.",()=>{game.solved=true;game.coins+=30;save();hud();dialogue("Queen Elowen","You found it! By royal decree, you are Guardian of Roseglass. Let the ball begin!",[["Watch the celebration",()=>stage(["you","queen"],"dance","The chandeliers come alive and everyone dances!",()=>move("ballroom"),2500)],["Explore the castle",scene]])},1700);dialogue("Queen Elowen","The Moonstone vanished just before tonight’s ball! Mara saw something strange near the old library. Will you help?",[["I’ll investigate",()=>{mark("queen");dialogue("Queen Elowen","Thank you. Speak with Mara, then visit the kitchens and library.",[["Start exploring",scene],["Speak to Mara",mara]])}],["I’d rather explore",scene]])}
function mara(){dialogue("Mara the Maid","Psst! I saw a shadow carry a velvet parcel behind the west bookshelf. Elin knows that room better than anyone.",[["Show me the library",()=>stage(["you","mara"],"walk","Mara leads you through the palace corridors.",()=>move("library"),1450)],["Ask about the parcel",()=>dialogue("Mara the Maid","It glittered blue in the candlelight. I think the old tower is involved!",[["Thank Mara",scene]])],["Keep exploring",scene]])}
function tomas(){if(has("Brass Key"))return dialogue("Tomas the Baker","That Brass Key should open a very old lock. Have another pastry for the road!",[["Take a honey bun",()=>stage(["tomas","you"],"give","Tomas hands you a warm pastry.",()=>{earn("Honey Bun");scene()})],["Thank Tomas",scene]]);dialogue("Tomas the Baker","I found an old key under the delivery basket. Help me finish this honey tart and you can have it.",[["Decorate the tart",()=>stage(["you","tomas"],"give","You decorate the tart; Tomas takes it to the oven.",()=>dialogue("Tomas the Baker","That’s perfect! You’ve earned the key.",[["Accept the Brass Key",()=>stage(["tomas","you"],"give","Tomas hands you the old Brass Key.",()=>{earn("Brass Key");mark("baked");scene()})]]),1900)],["Maybe later",scene]])}
function elin(){if(has("Clock Riddle"))return dialogue("Elin the Archivist","Remember: the answer is CLOCK. Bring your Brass Key to the ancient lock.",[["Go to the passage",()=>move("passage")],["Stay and browse",scene]]);dialogue("Elin the Archivist","A riddle protects the old tower: I have a face and two hands, yet I cannot smile. What am I?",[["A clock",()=>stage(["you","elin"],"give","Elin unrolls a parchment and hands it to you.",()=>{earn("Clock Riddle");scene()})],["A mirror",()=>dialogue("Elin the Archivist","Almost! But a mirror has no moving hands.",[["Try again",elin]])],["A statue",()=>dialogue("Elin the Archivist","Not quite. Think of something that keeps time.",[["Try again",elin]])],["Explore first",scene]])}
function inspect(id){if(busy)return;switch(id){
case"entrance":return stage(["you"],"walk","You push the heavy castle doors open.",()=>move("hall"));
case"fountain":if(!done("fountain")){game.coins+=5;mark("fountain");toast("You discovered 5 coins in the fountain!");}return dialogue("Narrator","The fountain water sparkles like silver.");
case"rose":earn("Garden Rose");return dialogue("Narrator","You pick a fragrant rose for your satchel.");
case"throne":return queen();
case"clock":return dialogue("Narrator","The grand clock strikes nine. Something clicks beneath the castle.");
case"tapestry":return stage(["you","mara"],"point","You lift the tapestry and discover an old stone doorway.",()=>dialogue("Mara the Maid","The entrance! But you still need a key.",[["Find the key",()=>move("kitchen")],["Explore",scene]]));
case"tart":case"basket":case"hearth":return tomas();
case"book":case"shelf":return elin();
case"globe":return dialogue("Narrator","One star on the globe points toward the castle’s abandoned tower.");
case"lantern":earn("Lit Lantern");return stage(["you"],"point","You light the lantern. Gold light fills the corridor.",scene);
case"stones":earn("Tower Crest");return dialogue("Narrator","A royal crest was concealed behind the stones.");
case"lock":if(!has("Brass Key"))return dialogue("Narrator","The heavy door needs an old Brass Key.");if(!has("Clock Riddle"))return dialogue("Narrator","You know you need a riddle. Ask Elin in the library.");return stage(["you"],"give","You insert the Brass Key and whisper CLOCK. The door opens!",()=>{mark("opened");move("tower")},2100);
case"mosaic":mark("mosaic");return dialogue("Narrator","Three silver emblems appear. The brightest one is a silver star.");
case"chest":if(has("Moonstone"))return dialogue("Narrator","The chest is open; you already have its treasure.");return dialogue("Narrator","The velvet chest has three emblems. Which one opens it?",[["Silver star",()=>stage(["you"],"give","The chest opens and blue moonlight fills the tower!",()=>{earn("Moonstone");dialogue("Narrator","You found the Moonstone! Return to Queen Elowen.",[["Return to the Grand Hall",()=>move("hall")],["Look around",scene]])},2000)],["Golden rose",()=>dialogue("Narrator","The lock stays closed. Check the star mosaic.",[["Try again",()=>inspect("chest")]])],["Brass clock",()=>dialogue("Narrator","That emblem sticks. Inspect the mosaic.",[["Try again",()=>inspect("chest")]])]]);
case"window":return dialogue("Narrator","The kingdom spreads out below you, glittering beneath the moon.");
case"music":return stage(["you"],"dance","The orchestra plays a lively waltz.",scene,1800);
case"dance":return stage(game.solved?["you","queen"]:["you"],"dance",game.solved?"You and the queen dance beneath the radiant chandeliers.":"You practice a graceful turn on the ballroom floor.",scene,2200);
case"lights":return dialogue("Narrator",game.solved?"The restored Moonstone makes the chandeliers shine like stars.":"The chandeliers wait for the missing Moonstone.");
case"pond":return dialogue("Narrator","A swan glides across the water. Nothing needs to be accomplished here.");
case"maze":return stage(["you"],"walk","You wander through the hedge maze and find a hidden rose garden.",()=>{earn("Silver Butterfly");scene()});
case"bench":return dialogue("Narrator","You rest under the roses. The castle can wait.");default:return scene();
}}
function mount(){el=document.createElement("section");el.id="roseglassGame";el.hidden=true;el.innerHTML='<header class="rc-hud"><div><small>STORYBOOK KINGDOM · PLAYABLE CASTLE</small><h1>🏰 Roseglass Castle</h1></div><div class="rc-controls"><strong id="rcCoins">🪙 0</strong><button id="rcRestart">↻ Restart</button><button id="rcExit">✕ Leave Castle</button></div></header><div class="rc-stage" id="rcStage" data-room="courtyard"><div class="rc-sky"></div><div class="rc-wall"><div class="rc-window">✦</div><div class="rc-window">✦</div><div class="rc-window">✦</div></div><div class="rc-floor"></div><div class="rc-candle left">🕯️</div><div class="rc-candle right">🕯️</div><h2 class="rc-title" id="rcTitle"></h2><p class="rc-subtitle" id="rcSubtitle"></p><div id="rcSpots" class="rc-spots"></div><div id="rcActors" class="rc-actors"></div><div id="rcToast" class="rc-toast" role="status"></div><div id="rcFade" class="rc-fade"></div></div><section class="rc-lower"><div class="rc-dialog"><strong id="rcWho"></strong><p id="rcLine"></p><div id="rcOptions"></div></div><aside class="rc-side"><strong id="rcQuest"></strong><h3>🗺️ Move to another room</h3><div id="rcDoors"></div><h3>🎒 Your Satchel</h3><div id="rcInventory"></div></aside></section>';document.body.appendChild(el);const g=id=>el.querySelector("#"+id);ui={stage:g("rcStage"),actors:g("rcActors"),spots:g("rcSpots"),doors:g("rcDoors"),toast:g("rcToast"),fade:g("rcFade"),title:g("rcTitle"),subtitle:g("rcSubtitle"),options:g("rcOptions"),who:g("rcWho"),text:g("rcLine"),coins:g("rcCoins"),inventory:g("rcInventory"),quest:g("rcQuest")};ui.actors.onclick=e=>{const a=e.target.closest("[data-person]");if(!a)return;if(a.dataset.person==="queen")queen();else if(a.dataset.person==="mara")mara();else if(a.dataset.person==="tomas")tomas();else if(a.dataset.person==="elin")elin();else toast("That is your character. Choose a person or an object!")};g("rcRestart").onclick=()=>{if(confirm("Restart the castle mystery? Your other kingdom saves will be kept.")){game=fresh();save();scene()}};g("rcExit").onclick=()=>{el.hidden=true;document.body.classList.remove("rc-playing")};function open(){el.hidden=false;document.body.classList.add("rc-playing");scene();if(!done("queen"))dialogue("Narrator","The golden castle doors open! The queen is waiting in the Grand Hall. You can begin the Moonstone mystery—or wander at your own pace.",[["Enter the Grand Hall",()=>move("hall")],["Explore outside first",scene]])}document.querySelector("#rgStartBtn")?.addEventListener("click",open);document.querySelector("#immersiveStartBtn")?.setAttribute("title","Classic caption-style mode");if(new URLSearchParams(location.search).has("castle"))open()}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",mount);else mount();
})();